# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "max-age=30758400"
[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "max-age=30758400"