[[redirects]]
  from = "/storybook"
  to = "/storybook/index.html"
  force = true

# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200